---
name: ClearPress
version: 335
author:
  - 'Roger M Pettett <rpettett@cpan.org>'
abstract: 'ClearPress - Simple, fresh & fruity MVC framework'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  CPAN: 1.9205
  Cwd: 3.2701
  File::Spec: 3.2701
  JSON: 2.12
  Test::Distribution: 0
  Test::More: 0.8
  Test::Perl::Critic: 0
  Test::Trap: v0.1.1
  XML::LibXML: 1.66
  XML::Simple: 2.18
  XML::TreeBuilder: 3.09
requires:
  CGI: 3.20
  Carp: 1.02
  Class::Accessor: 0.31
  Class::Singleton: 1.4
  Config::IniFiles: 2.38
  Crypt::Blowfish: 2.10
  Crypt::CBC: 2.30
  DBI: 1.51
  English: 1.01
  HTML::Entities: 1.35
  IO::Scalar: 2.110
  Lingua::EN::Inflect: 1.89
  MIME::Base64: 3.07
  POSIX: 1.09
  Readonly: 1.03
  Template: 2.19
  Template::Filters: 2.86
  XML::Simple: 2.18
  YAML::Tiny: 1.36
  base: 2.13
  strict: 1.03
  warnings: 1.05
recommends:
  DBD::SQLite: 1.14
  DBD::mysql: 4.007
  Net::LDAP: 0.39
configure_requires:
  Module::Build: 0.35
provides:
  ClearPress:
    file: lib/ClearPress.pm
    version: 318
  ClearPress::authdecor:
    file: lib/ClearPress/authdecor.pm
    version: 750
  ClearPress::authenticator:
    file: lib/ClearPress/authenticator.pm
    version: 740
  ClearPress::authenticator::ldap:
    file: lib/ClearPress/authenticator/ldap.pm
    version: 740
  ClearPress::authenticator::passwd:
    file: lib/ClearPress/authenticator/passwd.pm
    version: 740
  ClearPress::authenticator::session:
    file: lib/ClearPress/authenticator/session.pm
    version: 740
  ClearPress::controller:
    file: lib/ClearPress/controller.pm
    version: 335
  ClearPress::decorator:
    file: lib/ClearPress/decorator.pm
    version: 333
  ClearPress::driver:
    file: lib/ClearPress/driver.pm
    version: 287
  ClearPress::driver::SQLite:
    file: lib/ClearPress/driver/SQLite.pm
    version: 320
  ClearPress::driver::mysql:
    file: lib/ClearPress/driver/mysql.pm
    version: 279
  ClearPress::model:
    file: lib/ClearPress/model.pm
    version: 320
  ClearPress::util:
    file: lib/ClearPress/util.pm
    version: 320
  ClearPress::view:
    file: lib/ClearPress/view.pm
    version: 346
  ClearPress::view::error:
    file: lib/ClearPress/view/error.pm
    version: 320
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
