--- #YAML:1.0
name:                ClearPress
version:             174
abstract:            ~
license:             ~
author:              
    - Roger Pettett <rmp@sanger.ac.uk>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          1.02
    CGI:                           3.20
    Class::Accessor:               0.31
    Config::IniFiles:              2.38
    DBI:                           1.51
    English:                       1.01
    IO::Scalar:                    2.110
    Lingua::EN::Inflect:           1.89
    POSIX:                         1.09
    Template:                      2.19
    Template::Context:             2.98
    Test::More:                    0.8
    Test::Trap:                    0.1.1
    XML::TreeBuilder:              3.09
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
