---
name: ClearPress
version: 300
author:
  - 'Roger M Pettett <rpettett@cpan.org>'
abstract: 'ClearPress - Simple, fresh & fruity MVC framework'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CGI: 3.20
  Carp: 1.02
  Class::Accessor: 0.31
  Class::Singleton: 1.4
  Config::IniFiles: 2.38
  DBI: 1.51
  English: 1.01
  HTML::Entities: 1.35
  IO::Scalar: 2.110
  Lingua::EN::Inflect: 1.89
  POSIX: 1.09
  Readonly: 1.03
  Template: 2.19
  XML::Simple: 2.18
build_requires:
  CPAN: 1.9205
  Cwd: 3.2701
  File::Spec: 3.2701
  JSON: 2.12
  Test::Distribution: 0
  Test::More: 0.8
  Test::Perl::Critic: 0
  Test::Trap: 0.1.1
  XML::LibXML: 1.66
  XML::Simple: 2.18
  XML::TreeBuilder: 3.09
recommends:
  DBD::SQLite: 1.14
  DBD::mysql: 4.007
provides:
  ClearPress:
    file: lib/ClearPress.pm
    version: 279
  ClearPress::controller:
    file: lib/ClearPress/controller.pm
    version: 300
  ClearPress::decorator:
    file: lib/ClearPress/decorator.pm
    version: 279
  ClearPress::driver:
    file: lib/ClearPress/driver.pm
    version: 287
  ClearPress::driver::SQLite:
    file: lib/ClearPress/driver/SQLite.pm
    version: 300
  ClearPress::driver::mysql:
    file: lib/ClearPress/driver/mysql.pm
    version: 279
  ClearPress::model:
    file: lib/ClearPress/model.pm
    version: 300
  ClearPress::util:
    file: lib/ClearPress/util.pm
    version: 300
  ClearPress::view:
    file: lib/ClearPress/view.pm
    version: 300
  ClearPress::view::error:
    file: lib/ClearPress/view/error.pm
    version: 279
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
