# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ClearPress
version:      132
version_from: lib/ClearPress.pm
installdirs:  site
requires:
    Carp:                          1.02
    CGI:                           3.2
    DBI:                           1.51
    English:                       1.01
    IO::Scalar:                    2.11
    Lingua::EN::Inflect:           1.89
    POSIX:                         1.09
    Template:                      2.19

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
