#!/usr/local/bin/perl -wT
#########
# Author:        rmp
# Maintainer:    $Author: zerojinx $
# Created:       2007-03-28
# Last Modified: $Date: 2008-08-03 21:30:57 +0100 (Sun, 03 Aug 2008) $
# Id:            $Id: application 237 2008-08-03 20:30:57Z zerojinx $
# Source:        $Source: /cvsroot/clearpress/clearpress/cgi-bin/application,v $
# $HeadURL: https://zerojinx:@clearpress.svn.sourceforge.net/svnroot/clearpress/branches/prerelease-1.17/cgi-bin/application $
#
use strict;
use warnings;
use ClearPress::controller;

our $VERSION = do { my @r = (q$LastChangedRevision: 237 $ =~ /\d+/mxg); sprintf '%d.'.'%03d' x $#r, @r };

main();
0;

sub main {
  my $util = ClearPress::util->new();
  ClearPress::controller->handler($util);
}
